### ISSUE TITLE
Need help ?

### ISSUE THREAD

**Issue by benjaminhaeberli** [yassinedoghri/php-iconify#1]
Hi @yassinedoghri !

I was about to create a new `benjaminhaeberli/php-icons` repository to develop a PHP alternative to [blade-ui-kit/blade-icons](https://github.com/blade-ui-kit/blade-icons) (_need it for my non-Laravel projects_) and I came across your code, which looks great!

I noticed it's still in a `dev-develop` version at the moment, so I was wondering if you could use any help to release a `v1.0` ?

**Comment by yassinedoghri** [comment]
Hey @benjaminhaeberli,

Thanks for your interest in this project, really appreciate it! 🙂

I've been using this library for a few months now on [`ad-aures/castopod`](https://github.com/ad-aures/castopod) and it's been quite a good experience, haven't had any major issue with it.

I haven't released a `v1.0` yet because I just needed it for Castopod at that time and I figured there are still some missing pieces here and there, mainly automated tests and probably some docs (like a `CONTRIBUTING.md` file for example).  

> I noticed it's still in a dev-develop version at the moment, so I was wondering if you could use any help to release a v1.0 ?

I welcome any contribution :) And I wouldn't mind you trying it out and eventually opening any issue and/or even directly opening a PR for doc changes or bug fixes.

It's been a few months I haven't gone back to this so I'll think about the exact missing pieces for v1.0 and let you know.

**Comment by benjaminhaeberli** [comment]
Cool, thank @yassinedoghri ! Let's do that. By the way, I've just realised that we both speak French, but let's keep it English so that ~I can train mine~  other people who might want to contribute understand us 😆

> I haven't released a `v1.0` yet because I just needed it for Castopod at that time and I figured there are still some missing pieces here and there, mainly automated tests and probably some docs (like a `CONTRIBUTING.md` file for example).

Yes, some tests and `CONTRIBUTING.md` would great. I can make a PR for that, do you mind if I use [`pestphp/pest`](https://github.com/pestphp/pest/) ?

> I welcome any contribution :) And I wouldn't mind you trying it out and eventually opening any issue and/or even directly opening a PR for doc changes or bug fixes.
>
> It's been a few months I haven't gone back to this so I'll think about the exact missing pieces for v1.0 and let you know.

OK👍

**Comment by yassinedoghri** [comment]
> By the way, I've just realised that we both speak French, but let's keep it English so that ~I can train mine~ other people who might want to contribute understand us 😆

Oh yep, that's best 😄

> I can make a PR for that, do you mind if I use [pestphp/pest](https://github.com/pestphp/pest/) ?

No problem, thank you!

**Comment by yassinedoghri** [comment]
**[v1.0.0](https://github.com/yassinedoghri/php-icons/releases/tag/v1.0.0) was just released** :tada: 

I've worked on automating releases so that next releases go swiftly.

I think this can be closed now, thank you for your help! :pray:
